"""
Django settings for merchant_data_report project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env lives one level above the Django project root (in code,3,4,5,6/)
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-69c97$dch^0gd8p2#s51@rm8(p1gv=ux7h73z+r8ky)cycrvd1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Each review row has up to 4 dropdowns (province, district, municipality, gender).
# With hundreds of merchants the default 1000-field limit is easily exceeded.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'merchant',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'merchant_data_report.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'merchant_data_report.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# ── Hardcoded users — replaces Django auth. Reads via request.session['user']. ─
HARDCODED_USERS = {
    'admin':       {'password': 'admin123', 'full_name': 'System Administrator'},
    'nrb_officer': {'password': 'nrb2082',  'full_name': 'NRB Officer'},
    'jyotibikash': {'password': 'jbb2082',  'full_name': 'Jyoti Bikas Bank Officer'},
}

INSTITUTION_NAME = 'Jyoti Bikas Bank Limited'
INSTITUTION_CODE = '12060'

# ── Logging — user activity written to logs/activity.log, rotated daily ───────
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'activity': {'format': '%(message)s'},
    },
    'handlers': {
        'activity_file': {
            'class':       'logging.handlers.TimedRotatingFileHandler',
            'filename':    BASE_DIR / 'logs' / 'activity.log',
            'when':        'midnight',
            'interval':    1,
            'backupCount': 90,
            'encoding':    'utf-8',
            'formatter':   'activity',
            # delay=True defers opening the file until first write — avoids
            # Windows WinError 32 when Django auto-reloader holds the file
            # open in two processes during midnight rotation.
            'delay':       True,
        },
    },
    'loggers': {
        'merchant.activity': {
            'handlers':  ['activity_file'],
            'level':     'DEBUG',
            'propagate': False,
        },
    },
}
