# Generated by Django 5.1 on 2026-04-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CBSMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=100, unique=True, verbose_name='Merchant ID')),
                ('merchant_code', models.CharField(max_length=100, verbose_name='Merchant Code')),
                ('account_number', models.CharField(max_length=100, verbose_name='Account Number')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('municipality', models.CharField(max_length=100, verbose_name='Municipality')),
                ('address_1', models.CharField(max_length=255, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 2')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True, verbose_name='Gender')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
            ],
        ),
    ]
