# Generated by Django 5.1 on 2026-04-13 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_cbs_dob_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbsmerchant',
            name='merchant_code',
        ),
        migrations.RemoveField(
            model_name='cbsmerchant',
            name='merchant_id',
        ),
    ]
