# Generated by Django 5.1 on 2026-04-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_remove_merchant_id_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanCBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Account Number')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('municipality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipality')),
                ('address_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 2')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('C', 'Company')], max_length=10, null=True, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('country_code', models.CharField(blank=True, default='01', max_length=10, null=True, verbose_name='Country Code')),
            ],
            options={
                'verbose_name': 'Clean CBS Record',
                'verbose_name_plural': 'Clean CBS Records',
            },
        ),
    ]
