# Generated by Django 6.0.3 on 2026-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_rename_address2_to_address3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsmerchant',
            name='address_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 3'),
        ),
        migrations.AlterField(
            model_name='cleancbs',
            name='address_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 3'),
        ),
    ]
