# Generated by Django 5.1 on 2026-04-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_alter_cbsmerchant_address_3_alter_cleancbs_address_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleancbs',
            name='is_merchant',
            field=models.BooleanField(default=False, verbose_name='Is Merchant'),
        ),
    ]
