# Generated by Django 5.1 on 2026-04-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_cleancbs_is_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleancbs',
            name='is_merchant',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Is Merchant'),
        ),
    ]
