# Generated by Django 5.1 on 2026-04-21 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0008_alter_cleancbs_is_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_by', models.CharField(db_index=True, max_length=100)),
                ('generated_by_name', models.CharField(blank=True, max_length=200)),
                ('month', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('report_period', models.CharField(blank=True, max_length=50)),
                ('institution_name', models.CharField(default='Jyoti Bikas Bank Limited', max_length=200)),
                ('institution_code', models.CharField(default='12060', max_length=20)),
                ('unique_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('upload_filename', models.CharField(blank=True, max_length=255)),
                ('card_data_filename', models.CharField(blank=True, max_length=255)),
                ('phonepay_filename', models.CharField(blank=True, max_length=255)),
                ('nepalpay_filename', models.CharField(blank=True, max_length=255)),
                ('cardless_filename', models.CharField(blank=True, max_length=255)),
                ('mobile_banking_filename', models.CharField(blank=True, max_length=255)),
                ('connect_ips_filename', models.CharField(blank=True, max_length=255)),
                ('final_report_filename', models.CharField(blank=True, max_length=255)),
                ('total_records', models.IntegerField(default=0)),
                ('fonepay_count', models.IntegerField(default=0)),
                ('nepalpay_count', models.IntegerField(default=0)),
                ('invalid_account_count', models.IntegerField(default=0)),
                ('merged_cbs_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('has_errors', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report Batch',
                'verbose_name_plural': 'Report Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], db_index=True, default='INFO', max_length=10)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAIL', 'Login Failed'), ('LOGOUT', 'Logout'), ('GENERATE_START', 'Generate Started'), ('GENERATE_SUCCESS', 'Generate Success'), ('GENERATE_ERROR', 'Generate Error'), ('DOWNLOAD', 'Download'), ('VERIFY', 'Verified Report'), ('UNVERIFY', 'Unverified Report')], db_index=True, max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='merchant.reportbatch')),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
