# Generated by Django 5.1 on 2026-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0009_reportbatch_useractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'ordering': ['username'],
            },
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAIL', 'Login Failed'), ('LOGOUT', 'Logout'), ('GENERATE_START', 'Generate Started'), ('GENERATE_SUCCESS', 'Generate Success'), ('GENERATE_ERROR', 'Generate Error'), ('DOWNLOAD', 'Download'), ('VERIFY', 'Verified Report'), ('UNVERIFY', 'Unverified Report'), ('USER_CREATE', 'User Created'), ('USER_ROLE_CHANGE', 'User Role Changed'), ('USER_DEACTIVATE', 'User Deactivated'), ('USER_ACTIVATE', 'User Activated'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_CHANGE', 'Password Changed')], db_index=True, max_length=30),
        ),
    ]
